version: '3.9'

services:
  fake-cdn-api:
    container_name: storage-api
    build:
      context: .
      dockerfile: Dockerfile
    image: storage-api:latest
    environment:
      - ACCESS_KEY=${ACCESS_KEY}
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./data:/usr/src/app/data
    networks:
      - storage-api

networks:
  storage-api: